# Generated by Django 4.2 on 2025-05-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_backup_codes',
            field=models.TextField(blank=True, help_text='Comma-separated backup codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for MFA', max_length=32),
        ),
    ]
